import type { Metadata } from "next";
import { Comfortaa } from "next/font/google";
import "./globals.css";
import { Button } from "@/components/ui/button";
import Image from "next/image";
import Link from "next/link";
const inter = Comfortaa({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Solution",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
